port/wqueue: update latest work mechanism to get the time remaining
Change-Id: Ib5514d0787c3cbed9354d3c76d6a0f060003ff5b

diff --git a/.github/workflows/doc-build.yml b/.github/workflows/doc-build.yml
--- a/.github/workflows/doc-build.yml
+++ b/.github/workflows/doc-build.yml
@@ -3,31 +3,16 @@
 
 name: Documentation GitHub Workflow
 
-on:
-  pull_request:
-    paths:
-    - 'doc/**'
-    - '**.rst'
-    - 'include/**'
-    - 'kernel/include/kernel_arch_interface.h'
-    - 'lib/libc/**'
-    - 'subsys/testsuite/ztest/include/**'
-    - 'tests/**'
-    - '**/Kconfig*'
-    - 'west.yml'
-    - '.github/workflows/doc-build.yml'
-    - 'scripts/dts/**'
-    - 'scripts/requirements-doc.txt'
+on: [pull_request]
 
 jobs:
-  doc-build:
-    name: "Documentation Build"
+  build:
     runs-on: ubuntu-latest
 
     steps:
     - name: Update PATH for west
       run: |
-        echo "$HOME/.local/bin" >> $GITHUB_PATH
+        echo "::add-path::$HOME/.local/bin"
 
     - name: checkout
       uses: actions/checkout@v2
@@ -44,9 +29,10 @@ jobs:
 
     - name: install-pip
       run: |
-        sudo pip3 install -U setuptools wheel pip
+        pip3 install setuptools
         pip3 install -r scripts/requirements-doc.txt
-        pip3 install west==0.11.0
+        pip3 install west>=0.6.2
+        pip3 install pyelftools canopen progress
 
     - name: west setup
       run: |
@@ -55,7 +41,7 @@ jobs:
     - name: build-docs
       run: |
         source zephyr-env.sh
-        SPHINXOPTS="-q -W -j auto" make -C doc htmldocs
+        make htmldocs
         tar cvf htmldocs.tar --directory=./doc/_build html
 
     - name: upload-build
@@ -64,3 +50,15 @@ jobs:
       with:
         name: htmldocs.tar
         path: htmldocs.tar
+
+    - name: check-warns
+      run: |
+        if [ -s doc/_build/doc.warnings ]; then
+           docwarn=$(cat doc/_build/doc.warnings)
+           docwarn="${docwarn//'%'/'%25'}"
+           docwarn="${docwarn//$'\n'/'%0A'}"
+           docwarn="${docwarn//$'\r'/'%0D'}"
+           # We treat doc warnings as errors
+           echo "::error file=doc.warnings::$docwarn"
+           exit 1
+        fi
diff --git a/.github/workflows/doc-publish.yml b/.github/workflows/doc-publish.yml
--- a/.github/workflows/doc-publish.yml
+++ b/.github/workflows/doc-publish.yml
@@ -6,25 +6,19 @@ name: Doc build for Release or Daily
 # Either a daily based on schedule/cron or only on tag push
 on:
   schedule:
-    - cron:  '50 1/3 * * *'
+    - cron:  '50 22 * * *'
   push:
-    paths:
-      - 'VERSION'
     tags:
-      # only publish v* tags, do not care about zephyr-v* which point to the
-      # same commit
-      - 'v*'
+    - '*'
 
 jobs:
-  doc-publish:
-    name: Publish Documentation
+  build:
     runs-on: ubuntu-latest
-    if: github.repository == 'zephyrproject-rtos/zephyr'
 
     steps:
     - name: Update PATH for west
       run: |
-        echo "$HOME/.local/bin" >> $GITHUB_PATH
+        echo "::add-path::$HOME/.local/bin"
 
     - name: Determine tag
       id: tag
@@ -66,9 +60,10 @@ jobs:
 
     - name: install-pip
       run: |
-        sudo pip3 install -U setuptools wheel pip
-        pip3 install -r scripts/requirements-base.txt
+        pip3 install setuptools
         pip3 install -r scripts/requirements-doc.txt
+        pip3 install west>=0.6.2
+        pip3 install pyelftools
 
     - name: west setup
       run: |
@@ -79,7 +74,19 @@ jobs:
         DOC_TAG: ${{ steps.tag.outputs.TYPE }}
       run: |
         source zephyr-env.sh
-        make DOC_TAG=${DOC_TAG} -C doc htmldocs
+        make DOC_TAG=${DOC_TAG} htmldocs
+
+    - name: check-warns
+      run: |
+        if [ -s doc/_build/doc.warnings ]; then
+           docwarn=$(cat doc/_build/doc.warnings)
+           docwarn="${docwarn//'%'/'%25'}"
+           docwarn="${docwarn//$'\n'/'%0A'}"
+           docwarn="${docwarn//$'\r'/'%0D'}"
+           # We treat doc warnings as errors
+           echo "::error file=doc.warnings::$docwarn"
+           exit 1
+        fi
 
     - name: Upload to AWS S3
       env:
@@ -87,23 +94,18 @@ jobs:
       run: |
         echo "DOC_RELEASE=[$RELEASE]"
         if [ "$RELEASE" == "latest" ]; then
+           export
            echo "publish latest docs"
            aws s3 sync  --quiet doc/_build/html s3://docs.zephyrproject.org/latest --delete
            echo "success sync of latest docs"
         else
-           # we want just the version, without the leading 'v'
-           DOC_RELEASE=${RELEASE:1}
+           DOC_RELEASE=${RELEASE}.0
            echo "publish release docs: ${DOC_RELEASE}"
            aws s3 sync  --quiet doc/_build/html s3://docs.zephyrproject.org/${DOC_RELEASE}
            echo "success sync of rel docs"
         fi
         if [ -d doc/_build/doxygen/html ]; then
-           if [ "$RELEASE" == "latest" ]; then
-              API_RELEASE=latest
-           else
-              API_RELEASE=${RELEASE:1}
-           fi
-           echo "publish doxygen to apidoc/${API_RELEASE}"
-           aws s3 sync  --quiet doc/_build/doxygen/html s3://docs.zephyrproject.org/apidoc/${API_RELEASE} --delete
+           echo "publish doxygen"
+           aws s3 sync  --quiet doc/_build/doxygen/html s3://docs.zephyrproject.org/apidoc/${RELEASE} --delete
            echo "success publish of doxygen"
         fi
